# Generated by Django 3.0.7 on 2020-09-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200920_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default='title', max_length=90, unique=True, verbose_name='Title'),
        ),
    ]
