# Generated by Django 3.0.7 on 2020-11-25 10:29

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20201103_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=posts.models.upload_location, verbose_name='Image', width_field='image_width'),
        ),
    ]
