# Generated by Django 3.0.7 on 2020-07-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200715_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
